# Site settings
title: domtools
description: Tools for the Document Object Module
baseurl: /domtools
url: http://petrosh.github.io/domtools
github_username:  petrosh
permalink: pretty

# Files
js:
css:
  - normalize
  - github-markdown
  - github-syntax
  - primer-syntax
  - layout

# Defaults
defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      layout: "default"
      screenshot: false

# Gems
gems:
  - jekyll-github-metadata

repository: petrosh/domtools

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
